#!/bin/bash

echo "🚀 Deploy do Sistema de Banners Promocionais"
echo "============================================"
echo ""

# Backend
echo "📦 1. Backend (Render)"
echo "   - Model Banner no Prisma ✅"
echo "   - Migration 20260115164604_add_banners ✅"
echo "   - API /api/banners (5 endpoints) ✅"
echo "   - Rotas registradas no server.ts ✅"
echo ""

# Frontend - Management Page
echo "🎨 2. Frontend - Página de Gerenciamento"
echo "   - Arquivo: app/app/restaurant/[id]/banners/page.tsx ✅"
echo "   - Funcionalidades:"
echo "     * Lista de banners com preview"
echo "     * Modal criar/editar"
echo "     * Toggle ativo/inativo"
echo "     * Deletar banner"
echo "     * Color pickers (fundo e texto)"
echo "     * Upload de imagem (URL)"
echo "     * Posição (topo/meio/final)"
echo "     * Agendamento (data início/fim)"
echo ""

# Frontend - Dashboard Button
echo "🔘 3. Frontend - Botão no Dashboard"
echo "   - Script: add_banners_button.cjs"
echo "   - Execute: cd ../pronto.frontend && node ../pronto-backend/add_banners_button.cjs"
echo "   - Adiciona botão laranja 'Banners' ao lado de 'Cupons'"
echo ""

# Frontend - Public Display
echo "👁️  4. Frontend - Exibição Pública"
echo "   - Script: add_banners_to_menu.cjs"
echo "   - Execute: cd ../pronto.frontend && node ../pronto-backend/add_banners_button.cjs"
echo "   - Exibe banners ativos no topo do cardápio"
echo "   - Filtra por data (startDate <= now <= endDate)"
echo "   - Clickável se tiver linkUrl"
echo ""

# Deploy Steps
echo "📋 PASSOS PARA DEPLOY:"
echo "====================="
echo ""
echo "BACKEND (pronto-backend):"
echo "  git add ."
echo "  git commit -m 'feat: add promotional banners system'"
echo "  git push"
echo "  (Render fará deploy automático)"
echo ""
echo "FRONTEND (pronto.frontend):"
echo "  1. cd ../pronto.frontend"
echo "  2. node ../pronto-backend/add_banners_button.cjs"
echo "  3. node ../pronto-backend/add_banners_to_menu.cjs"
echo "  4. git add ."
echo "  5. git commit -m 'feat: add promotional banners UI'"
echo "  6. git push"
echo "  (Vercel fará deploy automático)"
echo ""

# Testing
echo "🧪 COMO TESTAR:"
echo "==============="
echo "1. Acesse o dashboard do restaurante"
echo "2. Clique no botão 'Banners'"
echo "3. Crie um novo banner:"
echo "   - Título: Promoção de Verão"
echo "   - Descrição: 20% OFF em todos os produtos"
echo "   - Cor de fundo: #10b981 (verde)"
echo "   - Cor do texto: #ffffff (branco)"
echo "   - Posição: Topo"
echo "   - Deixe ativo"
echo "4. Acesse o cardápio público (r/slug-do-restaurante)"
echo "5. Veja o banner exibido no topo"
echo "6. Clique no banner (se configurou linkUrl)"
echo ""

# API Endpoints
echo "📡 ENDPOINTS DA API:"
echo "==================="
echo "GET    /api/banners/restaurant/:restaurantId (auth)"
echo "       → Lista todos os banners do restaurante"
echo ""
echo "GET    /api/banners/public/:restaurantId/active"
echo "       → Lista banners ativos (público, com filtro de data)"
echo ""
echo "POST   /api/banners (auth)"
echo "       → Cria novo banner"
echo "       Body: { restaurantId, title, description?, imageUrl?,"
echo "               linkUrl?, backgroundColor, textColor, position,"
echo "               sortOrder, startDate?, endDate? }"
echo ""
echo "PUT    /api/banners/:id (auth)"
echo "       → Atualiza banner (todos os campos opcionais)"
echo ""
echo "DELETE /api/banners/:id (auth)"
echo "       → Deleta banner"
echo ""

# Database Schema
echo "🗄️  SCHEMA DO BANCO:"
echo "==================="
echo "model Banner {"
echo "  id              String    @id @default(uuid())"
echo "  restaurantId    String"
echo "  restaurant      Restaurant @relation(fields: [restaurantId], references: [id], onDelete: Cascade)"
echo "  title           String"
echo "  description     String?"
echo "  imageUrl        String?"
echo "  linkUrl         String?"
echo "  backgroundColor String    @default(\"#10b981\")"
echo "  textColor       String    @default(\"#ffffff\")"
echo "  position        String    @default(\"top\")"
echo "  sortOrder       Int       @default(0)"
echo "  startDate       DateTime?"
echo "  endDate         DateTime?"
echo "  isActive        Boolean   @default(true)"
echo "  createdAt       DateTime  @default(now())"
echo "  updatedAt       DateTime  @updatedAt"
echo ""
echo "  @@index([restaurantId])"
echo "  @@index([isActive])"
echo "  @@index([position])"
echo "  @@index([sortOrder])"
echo "}"
echo ""

echo "✅ Sistema de Banners Promocionais pronto para deploy!"
echo "🎯 Próximo: Ofertas por tempo limitado"
