services:
  - type: web
    name: pronto-backend
    env: node
    plan: free
    buildCommand: npm ci && npm run build && npm run prisma:migrate
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
